### PR TITLE
Update syn to 2.0

### PR DESCRIPTION
**Pull request by messense**
https://github.com/dtolnay/syn/releases/tag/2.0.0

### CODE REVIEW

**Review by m4b — APPROVED** [review]

**Comment by mkroening** [comment]
@m4b, it would be wonderful to publish a release with this. :)

**Comment by m4b** [comment]
sorry for the long delay here, published in 0.11.1

**Comment by m4b** [comment]
btw @mkroening rusty hermit is a very cool project, hope it continues and you all are doing well, very exciting stuff :)

**Comment by mkroening** [comment]
> sorry for the long delay here, published in 0.11.1

No worries! Thanks a lot!

> btw @mkroening rusty hermit is a very cool project, hope it continues and you all are doing well, very exciting stuff :)


Thanks! You saying that really means a lot to us. Keep up the awesome work :)

**Pull request merged**
